### ISSUE TITLE
parse_leaderboard': undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by pavlov0032** [stephenwong/strava_club_activities#1]
Hi!

I'm getting an error

Traceback (most recent call last):
	2: from bin/club_activities:53:in `<main>'
	1: from /Users/alexeipavlov/Documents/strava_club_activities-master/lib/strava_club_activities/processor/segment_race.rb:20:in `process'
/Users/alexeipavlov/Documents/strava_club_activities-master/lib/strava_club_activities/parser/segment_activities.rb:31:in `parse_leaderboard': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by KinDzaDza1** [comment]
strava_club_activities-master % bundle exec ruby bin/club_activities  --mode segment --access-token 71876b74003629e6d3e3cf98755409e67c6b7298  --filter Chicken Head DH
